In [1]:
!pip install ydata-profiling pyjanitor great-expectations dvc -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 16.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 277.1/277.1 kB 16.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 78.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 470.1/470.1 kB 26.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.3/79.3 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 451.2/451.2 kB 19.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.8/155.8 kB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 34.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.2/214.2 kB 10.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 63.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 29.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.1/118.1 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.2/74.2 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 40.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.2/381.2 kB 20.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.1/87.1 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 4.2 MB/s eta 0:00:00

In [2]:
from google.colab import files

uploaded = files.upload()

Saving merged_layoffs-2.csv to merged_layoffs-2.csv

In [3]:
import pandas as pd
from ydata_profiling import ProfileReport

/tmp/ipykernel_3471/2829373970.py:2: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [4]:
df = pd.read_csv("merged_layoffs-2.csv")

df.head()

,source_file,company,location_hq,region,us_state,country,continent,total_laid_off,date,percentage_laid_off,...,industry,stage,funds_raised_mil,year,latitude,longitude,source,status,additional_notes,date_added
0,e9790953__e712c4d3-c545-4ed7-8062-2e2df048dda8...,Tamara Mellon,Los Angeles,other,California,USA,North America,20,2020-03-12,40.0,...,Retail,Series C,90.0,2020.0,34.053691,-118.242766,NaN,NaN,NaN,NaN
1,e9790953__e712c4d3-c545-4ed7-8062-2e2df048dda8...,HopSkipDrive,Los Angeles,other,California,USA,North America,8,2020-03-13,10.0,...,Transportation,Unknown,45.0,2020.0,34.053691,-118.242766,NaN,NaN,NaN,NaN
2,e9790953__e712c4d3-c545-4ed7-8062-2e2df048dda8...,Panda Squad,San Francisco,San Francisco Bay Area,California,USA,North America,6,2020-03-13,75.0,...,Consumer,Seed,1.0,2020.0,37.779259,-122.419329,NaN,NaN,NaN,NaN
3,e9790953__e712c4d3-c545-4ed7-8062-2e2df048dda8...,Help.com,Austin,other,Texas,USA,North America,16,2020-03-16,100.0,...,Support,Seed,6.0,2020.0,30.271129,-97.743700,NaN,NaN,NaN,NaN
4,e9790953__e712c4d3-c545-4ed7-8062-2e2df048dda8...,Inspirato,Denver,other,Colorado,USA,North America,130,2020-03-16,22.0,...,Travel,Series C,79.0,2020.0,39.739236,-104.984862,NaN,NaN,NaN,NaN

In [5]:
print("Shape:", df.shape)

print("\nColumns")
print(df.columns)

print("\nData Types")
print(df.dtypes)

print("\nMissing Values")
print(df.isnull().sum())

Shape: (7441, 22)

Columns
Index(['source_file', 'company', 'location_hq', 'region', 'us_state',
       'country', 'continent', 'total_laid_off', 'date', 'percentage_laid_off',
       'company_size_before', 'company_size_after', 'industry', 'stage',
       'funds_raised_mil', 'year', 'latitude', 'longitude', 'source', 'status',
       'additional_notes', 'date_added'],
      dtype='object')

Data Types
source_file             object
company                 object
location_hq             object
region                  object
us_state                object
country                 object
continent               object
total_laid_off          object
date                    object
percentage_laid_off     object
company_size_before    float64
company_size_after     float64
industry                object
stage                   object
funds_raised_mil       float64
year                   float64
latitude               float64
longitude              float64
source                  object
status                  object
additional_notes        object
date_added              object
dtype: object

Missing Values
source_file               0
company                   0
location_hq               1
region                 5029
us_state               5030
country                 491
continent              5029
total_laid_off         1942
date                      0
percentage_laid_off    2142
company_size_before    5672
company_size_after     7441
industry                  2
stage                   661
funds_raised_mil       1390
year                   5029
latitude               5029
longitude              5029
source                 2415
status                 6952
additional_notes       7419
date_added             2901
dtype: int64

In [6]:
profile = ProfileReport(
    df,
    title="Layoffs Dataset Profiling Report",
    explorative=True
)

profile.to_file("profiling_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/22 [00:00<?, ?it/s]
  5%|▍         | 1/22 [00:00<00:02,  8.65it/s]
  9%|▉         | 2/22 [00:00<00:02,  9.05it/s]
 14%|█▎        | 3/22 [00:00<00:02,  8.00it/s]
 23%|██▎       | 5/22 [00:00<00:01, 11.26it/s]
 36%|███▋      | 8/22 [00:00<00:00, 14.47it/s]
 50%|█████     | 11/22 [00:00<00:00, 16.96it/s]
 68%|██████▊   | 15/22 [00:00<00:00, 21.05it/s]
100%|██████████| 22/22 [00:01<00:00, 15.74it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [7]:
from google.colab import files

files.download("profiling_report.html")

In [12]:
print("Before:", df.shape)

df = df.drop_duplicates().copy()

print("After:", df.shape)

Before: (7435, 29)
After: (7435, 29)

In [13]:
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    df[col] = df[col].fillna("Unknown")

print(df.isnull().sum())

source_file               0
company                   0
location_hq               0
region                    0
us_state                  0
country                   0
continent                 0
total_laid_off            0
date                   5029
percentage_laid_off       0
company_size_before       0
company_size_after     7435
industry                  0
stage                     0
funds_raised_mil          0
year                      0
latitude                  0
longitude                 0
source                    0
status                    0
additional_notes          0
date_added                0
Year                      0
Month                     0
Quarter                   0
Day                       0
DayOfWeek                 0
IsWeekend                 0
TimeOfDay                 0
dtype: int64

In [14]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")

In [15]:
df["Year"] = df["date"].dt.year
df["Month"] = df["date"].dt.month
df["Quarter"] = df["date"].dt.quarter
df["Day"] = df["date"].dt.day
df["DayOfWeek"] = df["date"].dt.day_name()
df["IsWeekend"] = df["date"].dt.weekday >= 5

# Since there is no time column
df["TimeOfDay"] = "Unknown"

df.head()

,source_file,company,location_hq,region,us_state,country,continent,total_laid_off,date,percentage_laid_off,...,status,additional_notes,date_added,Year,Month,Quarter,Day,DayOfWeek,IsWeekend,TimeOfDay
0,e9790953__e712c4d3-c545-4ed7-8062-2e2df048dda8...,Tamara Mellon,Los Angeles,other,California,USA,North America,20,2020-03-12,40.0,...,Unknown,Unknown,Unknown,2020.0,3.0,1.0,12.0,Thursday,False,Unknown
1,e9790953__e712c4d3-c545-4ed7-8062-2e2df048dda8...,HopSkipDrive,Los Angeles,other,California,USA,North America,8,2020-03-13,10.0,...,Unknown,Unknown,Unknown,2020.0,3.0,1.0,13.0,Friday,False,Unknown
2,e9790953__e712c4d3-c545-4ed7-8062-2e2df048dda8...,Panda Squad,San Francisco,San Francisco Bay Area,California,USA,North America,6,2020-03-13,75.0,...,Unknown,Unknown,Unknown,2020.0,3.0,1.0,13.0,Friday,False,Unknown
3,e9790953__e712c4d3-c545-4ed7-8062-2e2df048dda8...,Help.com,Austin,other,Texas,USA,North America,16,2020-03-16,100.0,...,Unknown,Unknown,Unknown,2020.0,3.0,1.0,16.0,Monday,False,Unknown
4,e9790953__e712c4d3-c545-4ed7-8062-2e2df048dda8...,Inspirato,Denver,other,Colorado,USA,North America,130,2020-03-16,22.0,...,Unknown,Unknown,Unknown,2020.0,3.0,1.0,16.0,Monday,False,Unknown

In [16]:
df.to_csv("cleaned_layoffs.csv", index=False)

print("Dataset Saved Successfully!")

Dataset Saved Successfully!

In [17]:
files.download("cleaned_layoffs.csv")

In [19]:
!pip install pandera -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 447.8/447.8 kB 9.7 MB/s eta 0:00:00

In [32]:
import pandera as pa
from pandera import Column, DataFrameSchema, Check

schema = DataFrameSchema({
    "company": Column(str, nullable=False),
    "country": Column(str, nullable=False),
    "total_laid_off": Column(float, Check.ge(0), nullable=True),
    "year": Column(int, Check.in_range(2000, 2035), nullable=True)
})

validated_df = schema.validate(df)

print("✅ Dataset validation successful!")

✅ Dataset validation successful!

In [34]:
validated_df.to_csv("validated_cleaned_layoffs.csv", index=False)

In [36]:
import json
files.download("validation_report.json")

In [37]:
!git init

!dvc init

!dvc add cleaned_layoffs.csv

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/
Initialized DVC repository.

You can now commit the changes to git.

+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|             <https://dvc.org/doc/user-guide/analytics>              |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: <https://dvc.org/doc>
- Get help and share ideas: <https://dvc.org/chat>
- Star us on GitHub: <https://github.com/treeverse/dvc>
⠋ Checking graph
Adding...:   0% 0/1 [00:00<?, ?file/s{'info': ''}]
!
          |0.00 [00:00,     ?file/s]

!
  0% |          |0/? [00:00<?,    ?files/s]

Adding cleaned_layoffs.csv to cache:   0% 0/1 [00:00<?, ?file/s]
Adding cleaned_layoffs.csv to cache:   0% 0/1 [00:00<?, ?file/s{'info': ''}]

Checking out /content/cleaned_layoffs.csv:   0% 0/1 [00:00<?, ?files/s]
  0% 0/1 [00:00<?, ?files/s{'info': ''}]
Adding...: 100% 1/1 [00:00<00:00, 18.80file/s{'info': ''}]

To track the changes with git, run:

	git add .gitignore cleaned_layoffs.csv.dvc

To enable auto staging, run:

	dvc config core.autostage true